### ISSUE TITLE
Add the treemap data visualisation type

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#136]
- [ ] Locate example data on PMD
- [ ] Add the additional visualisation type
- [ ] Conditionally show the relevant properties for the visualisation type
- [ ] Update the data connectors if necessary 
- [ ] Update the data column, series assignment and series properties logic if necessary
- [ ] Render the chart with data and configured properties

**Comment by JasonHowell** [comment]
This is nearly a year old and no user research to support the request.  Closing.
