### ISSUE TITLE
Use plotly modules/bundles

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/chart-builder#138]
According to https://github.com/plotly/plotly.js/blob/master/dist/README.md

> The main plotly.js bundles weight in at:
> 
> | plotly.js | plotly.min.js | plotly.min.js + gzip | plotly-with-meta.js |
> |-----------|---------------|----------------------|---------------------|
> | 8.4 MB | 3.5 MB | 1 MB | 8.7 MB |

However, we may be able to get away with some smaller subset of bundles, e.g.:

[plotly.js basic](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-basic)

> | Raw size | Minified size | Minified + gzip size |
> |------|-----------------|------------------------|
> | 2.7 MB | 997.9 kB | 324.5 kB |

and [plotly.js geo](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-geo)

> | Raw size | Minified size | Minified + gzip size |
> |------|-----------------|------------------------|
> | 3.1 MB | 1.1 MB | 367.2 kB |

for a bit of a smaller overall download.

**Comment by charlesons** [comment]
Suggested approach doesn't work as we are using `react-plotly`. An alternative solution outlined here may however prove useful:

https://github.com/plotly/react-plotly.js/issues/98
