### ISSUE TITLE
Problem creating stacked bar chart for CCv2 Impacts Dashboard: Status of surface waters in England, 2019

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#139]
Attempting to recreate the chart 

https://climate-change.data.gov.uk/impacts

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/05e4088a-d9fd-4b4e-b7f5-1657e08e59ce)

The following issues exist and need fixing:

- [ ] The All surface water bodies stacked bar adds up to 200% but should be 100%
- [ ] The chart is missing a stacked bar for Rivers: plants and algae
- [ ] The axis labels for horizontal bar charts cannot be truncated

**Comment by charlesons** [comment]
Investigating whether this is a chart builder capability issue or a dataset issue

**Comment by TahaRana97** [comment]
@rossbowen @ajtucker to review this PR once ready
