### ISSUE TITLE
Resolve dependabot security alerts

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#180]
https://github.com/GSS-Cogs/chart-builder/security/dependabot

**Comment by eldeal** [comment]
Discuss in planning, there's a group that will all go together nicely

**Comment by eldeal** [comment]
Some shared with other repos, look at fixing everywhere

**Comment by eldeal** [comment]
Removing storybook (or updating) and bumping volto to 16 are all on the table as possible improvements in this space

**Comment by JasonHowell** [comment]
Story point needs to be address.

**Comment by StRhys** [comment]
https://github.com/GSS-Cogs/chart-builder/pull/199
https://github.com/GSS-Cogs/chart-builder/pull/198
