### ISSUE TITLE
Restrict or manage the length of axis tick labels to prevent them distorting the display of the chart

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#56]

**Comment by charlesons** [comment]
The Plotly API seems not to offer any control over tick label lengths:

https://stackoverflow.com/questions/66504218/is-it-possible-to-limit-or-truncate-the-characters-of-the-tick-label-in-plotly

Implemented a function to truncate the x series labels and an associated property in the chart properties configurator.

**Comment by nosnickid** [comment]
Looks good to me
