### ISSUE TITLE
Choropleth maps feature

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#57]

**Comment by TahaRana97** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/chart-builder/57?planning-poker) with ZenHub @nosnickid @ajtucker @charlesons

**Comment by charlesons** [comment]
Ploty choropleth maps don't offer us a way to control the extent of zoom. This can lead to the map being zoomed to undesirable states where the user can no longer locate the map because it is too small or the zoom level is so great as to not offer any meaningful data visualisation.

There is an open issue with plotly from October 2020 https://github.com/plotly/plotly.js/issues/5191

**Comment by charlesons** [comment]
Legislation on website accessibility for public bodies - maps seem not to be covered by the legislation (see section 2d)  

https://www.legislation.gov.uk/uksi/2018/952/regulation/4/made

**Comment by nosnickid** [comment]
Awaiting a PR merge then ready to close

**Comment by nosnickid** [comment]
Closed by #70
