### ISSUE TITLE
Create and maintain an inventory of the properties that chart builder controls

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#60]
Create and maintain an inventory of the properties that chart builder controls - both user-configurable and designer specified.

**Comment by ajtucker** [comment]
Manually write up in wiki a clear description of properties and their meaning.

**Comment by charlesons** [comment]
https://github.com/GSS-Cogs/chart-builder/wiki/Inventory-of-chart-and-map-properties

**Comment by charlesons** [comment]
Linked to #73

**Comment by nosnickid** [comment]
Wiki page matches the most recent tweaks to separate chart properties schema from values. Looks good to me.
