### ISSUE TITLE
Stacked bar chart totals

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#61]
For stacked bar charts show a total in the hover text for the stack as well as for the hovered bar

**Comment by charlesons** [comment]
The implementation shown above (from the CC1 dashboard) is actually a combined bar and line chart - with the line chart element showing only the plot points). 

Task should be expanded / replaced to create a combined line and bar chart type.

**Comment by TahaRana97** [comment]
Moving back to product backlog - needs further definition and discussion with product owner/customers

**Comment by charlesons** [comment]
Across series totals aren't provided by default in Plotly so these were calculated and assigned to the `customdata` property of the traces and then included in the hovertemplate `%{customdata}`. This functionality isn't included in the Plotly [docs](https://plotly.com/javascript/hover-text-and-formatting/) but is explained in a forum [post](https://community.plotly.com/t/hovertemplate-with-customdata/36080)
