### ISSUE TITLE
Visualise uncertainty through confidence intervals and error bars

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/chart-builder#94]
- [ ] Add the capability to visualise uncertainty of line chart data series using confidence intervals and error bars
- [ ] Prove the feature out with CIS data

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/855c0e32-1d8e-4858-a87b-89f97fda508f)

Source:
https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/bulletins/coronaviruscovid19infectionsurveypilot/14april2022

**Comment by eldeal** [comment]
Believe CIS label is no longer relevant, DCMS team have the more pressing needs in this space
